sudo: false
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - jruby-19mode
before_script:
  - gem install bundler # To use bundler 1.10 or later
gemfile:
  - gemfiles/rails32_ember_113.gemfile
  - gemfiles/rails40_ember_113.gemfile
  - gemfiles/rails41_ember_113.gemfile
  - gemfiles/rails42_ember_113.gemfile
  - gemfiles/rails32_ember_18.gemfile
  - gemfiles/rails40_ember_18.gemfile
  - gemfiles/rails41_ember_18.gemfile
  - gemfiles/rails42_ember_18.gemfile
  - gemfiles/rails32_ember_latest.gemfile
  - gemfiles/rails40_ember_latest.gemfile
  - gemfiles/rails41_ember_latest.gemfile
  - gemfiles/rails42_ember_latest.gemfile
  - gemfiles/sprockets_3.gemfile
  - gemfiles/sprockets_rails_3.gemfile
